---
version: "2.0"

services:
  app:
    image: tombeynon/helium-on-akash:v0.0.3
    env:
      - AWS_ACCESS_KEY=mykey
      - AWS_SECRET_KEY=mysecret
      - S3_KEY_PATH=mybucket/miner1/swarm_key
    expose:
      - port: 2154
        as: 2154
        to:
          - global: true

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 32Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        app:
          denom: uakt
          amount: 20

deployment:
  app:
    dcloud:
      profile: app
      count: 1
